apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-client
  template:
    metadata:
      labels:
        app: next-client
    spec:
      containers:
      - name: next-client
        image: daspratha/nextjs_express:next-client
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: next-service
spec:
  type: NodePort
  selector:
    app: next-client
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30002
