---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-admin-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin # ClusterRole name Default on EKS, not need to create a seperate ClusterRole for Admins
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: admins # Group name
    apiGroup: rbac.authorization.k8s.io


# For Admins, we dont need to create seperate role/clusterrole on k8s, we can refer to K8s own "cluster-admin" role