apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole  # ClusterRole name Default on EKS, no need to create a separate ClusterRole for Admins
  name: cluster-admin
subjects:
- kind: Group
  name: Admin-Group  # This matches the Kubernetes group defined in aws_eks_access_entry
  apiGroup: rbac.authorization.k8s.io
