---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ergonnex-net
  namespace: istio-ingress
spec:
  secretName: istio-ergonnex-net
  dnsNames:
    - istio.ergonnex.net
  issuerRef:
    name: http-01-production
    kind: ClusterIssuer
    group: cert-manager.io