---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-lia-net
  namespace: istio-ingress
spec:
  secretName: istio-lia-net
  dnsNames:
    - istio.lia.com
  issuerRef:
    name: http-01-production
    kind: ClusterIssuer
    group: cert-manager.io