#This secret is made using the Nexus url, username & password 
# The JSON from which this secret is made
# cat dockerconfig.json | base64
# dockerconfig.json
# {"auths":{"https://nexus.domain.com":{"username":"argo-user","password":"fake-password","email":"partho.das@domain.com"}}}


---
apiVersion: v1
kind: Secret
metadata:
  name: nexuscreds
  namespace: application_deployment_ns
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJod29ubmV4Lm5ldCI6eyJ1c2VybmFtZSI6ImVyZy1hcmdvLXVzZXIiLCJwYXNzd29yZCI6IkVyZ29ubmV4JDk5MDAiLCJlbWFpbCI6InBhcnRoby5kYXNAZXJnb25uZXguY29tIn19fQo=