apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-pods
spec:
  podSelector:
    matchLabels:
      app: isolated-deployment
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: express-deployment
