apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    app: my_app
    type: fe
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
apiVersion: v1

kind: ReplicationController

metadata: # Tells about the object itself
  name: my_rc
  labels:
    app: my_app
    type: fe

spec: # This defines the object that it is going to build
  template:  # template of the pod that the object is for
    metadata:
      name: nginx-pod
      labels: 
        app: my_app
        type: fe
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
  replicas: 2

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my_rs
  labels:
    app: my_app
    type: fe
spec:
  replicas: 2
  selector: 
    matchLabels:
      type: fe
  template:
    metadata:
      name: nginx-pod
      labels: 
        app: my_app
        type: fe
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2


---

apiVersion: v1 # These are objects {}
kind: Pod
metadata:
  name: my_pod
  labels:
    type: fe
spec:
  containers:
    - name: nginx_container #This indicates List []
      image: nginx

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my_rs
  labels:
    type: fe
    count: 4
spec: 
  replicas: 2
  selector:
    matchLabels:
      type: fe
  template:
    metadata:
      name: my_pod
      labels:
        type: fe
    spec:
      containers:
        - name: nginx_container #This indicates List []
          image: nginx

